// Package iso3166 provides basic country lookup functionality.
package iso3166

import "strings"

/*
* adapted from: https://djangocas.dev/blog/posts/ios-3166-country-codes-json/
 */

type Country struct {
	Name   string
	Alpha2 string
	Alpha3 string
}

var Countries = []Country{
	{"Afghanistan", "AF", "AFG"},
	{"Albania", "AL", "ALB"},
	{"Algeria", "DZ", "DZA"},
	{"American Samoa", "AS", "ASM"},
	{"Andorra", "AD", "AND"},
	{"Angola", "AO", "AGO"},
	{"Anguilla", "AI", "AIA"},
	{"Antigua and Barbuda", "AG", "ATG"},
	{"Argentina", "AR", "ARG"},
	{"Armenia", "AM", "ARM"},
	{"Aruba", "AW", "ABW"},
	{"Australia", "AU", "AUS"},
	{"Austria", "AT", "AUT"},
	{"Azerbaijan", "AZ", "AZE"},
	{"Bahamas", "BS", "BHS"},
	{"Bahrain", "BH", "BHR"},
	{"Bangladesh", "BD", "BGD"},
	{"Barbados", "BB", "BRB"},
	{"Belarus", "BY", "BLR"},
	{"Belgium", "BE", "BEL"},
	{"Belize", "BZ", "BLZ"},
	{"Benin", "BJ", "BEN"},
	{"Bermuda", "BM", "BMU"},
	{"Bhutan", "BT", "BTN"},
	{"Bolivia", "BO", "BOL"},
	{"Bosnia and Herzegovina", "BA", "BIH"},
	{"Botswana", "BW", "BWA"},
	{"Brazil", "BR", "BRA"},
	{"British Virgin Islands", "VG", "VGB"},
	{"Brunei Darussalam", "BN", "BRN"},
	{"Bulgaria", "BG", "BGR"},
	{"Burkina Faso", "BF", "BFA"},
	{"Burundi", "BI", "BDI"},
	{"Cambodia", "KH", "KHM"},
	{"Cameroon", "CM", "CMR"},
	{"Canada", "CA", "CAN"},
	{"Cape Verde", "CV", "CPV"},
	{"Central African Republic", "CF", "CAF"},
	{"Chad", "TD", "TCD"},
	{"Chile", "CL", "CHL"},
	{"China", "CN", "CHN"},
	{"Hong Kong", "HK", " HKG"},
	{"Macao", "MO", "MAC"},
	{"Colombia", "CO", "COL"},
	{"Comoros", "KM", "COM"},
	{"Congo", "CG", "COG"},
	{"Costa Rica", "CR", "CRI"},
	{"Côte d'Ivoire", "CI", "CIV"},
	{"Croatia", "HR", "HRV"},
	{"Cuba", "CU", "CUB"},
	{"Cyprus", "CY", "CYP"},
	{"Czech Republic", "CZ", "CZE"},
	{"Denmark", "DK", "DNK"},
	{"Djibouti", "DJ", "DJI"},
	{"Dominica", "DM", "DMA"},
	{"Dominican Republic", "DO", "DOM"},
	{"Ecuador", "EC", "ECU"},
	{"Egypt", "EG", "EGY"},
	{"El Salvador", "SV", "SLV"},
	{"Equatorial Guinea", "GQ", "GNQ"},
	{"Eritrea", "ER", "ERI"},
	{"Estonia", "EE", "EST"},
	{"Ethiopia", "ET", "ETH"},
	{"European Union", "EU", ""},
	{"Faroe Islands", "FO", "FRO"},
	{"Fiji", "FJ", "FJI"},
	{"Finland", "FI", "FIN"},
	{"France", "FR", "FRA"},
	{"French Guiana", "GF", "GUF"},
	{"French Polynesia", "PF", "PYF"},
	{"Gabon", "GA", "GAB"},
	{"Gambia", "GM", "GMB"},
	{"Georgia", "GE", "GEO"},
	{"Germany", "DE", "DEU"},
	{"Ghana", "GH", "GHA"},
	{"Greece", "GR", "GRC"},
	{"Greenland", "GL", "GRL"},
	{"Grenada", "GD", "GRD"},
	{"Guadeloupe", "GP", "GLP"},
	{"Guam", "GU", "GUM"},
	{"Guatemala", "GT", "GTM"},
	{"Guinea-Bissau", "GW", "GNB"},
	{"Haiti", "HT", "HTI"},
	{"Honduras", "HN", "HND"},
	{"Hungry", "HU", "HUN"},
	{"Iceland", "IS", "ISL"},
	{"India", "IN", "IND"},
	{"Indonesia", "ID", "IDN"},
	{"Iran (Islamic Republic of)", "IR", "IRN"},
	{"Iraq", "IQ", "IRQ"},
	{"Ireland", "IE", "IRL"},
	{"Israel", "IL", "ISR"},
	{"Italy", "IT", "ITA"},
	{"Japan", "JP", "JPN"},
	{"Jordan", "JO", "JOR"},
	{"Kazakhstan", "KZ", "KAZ"},
	{"Kenya", "KE", "KEN"},
	{"Kiribati", "KI", "KIR"},
	{"North Korea", "KP", "PRK"},
	{"South Korea", "KR", "KOR"},
	{"Kuwait", "KW", "KWT"},
	{"Kyrgyzstan", "KG", "KGZ"},
	{"Lao PDR", "LA", "LAO"},
	{"Latvia", "LV", "LVA"},
	{"Lebanon", "LB", "LBN"},
	{"Lesotho", "LS", "LSO"},
	{"Liberia", "LR", "LBR"},
	{"Libya", "LY", "LBY"},
	{"Liechtenstein", "LI", "LIE"},
	{"Lithuania", "LT", "LTU"},
	{"Luxembourg", "LU", "LUX"},
	{"Madagascar", "MG", "MDG"},
	{"Malawi", "MW", "MWI"},
	{"Malaysia", "MY", "MYS"},
	{"Maldives", "MV", "MDV"},
	{"Mali", "ML", "MLI"},
	{"Malta", "MT", "MLT"},
	{"Marshall Islands", "MH", "MHL"},
	{"Martinique", "MQ", "MTQ"},
	{"Mauritania", "MR", "MRT"},
	{"Mauritius", "MU", "MUS"},
	{"Mexico", "MX", "MEX"},
	{"Micronesia, Federated States of", "FM", "FSM"},
	{"Moldova", "MD", "MDA"},
	{"Monaco", "MC", "MCO"},
	{"Mongolia", "MN", "MNG"},
	{"Montenegro", "ME", "MNE"},
	{"Montserrat", "MS", "MSR"},
	{"Morocco", "MA", "MAR"},
	{"Mozambique", "MZ", "MOZ"},
	{"Myanmar", "MM", "MMR"},
	{"Namibia", "NA", "NAM"},
	{"Nauru", "NR", "NRU"},
	{"Nepal", "NP", "NPL"},
	{"Netherlands", "NL", "NLD"},
	{"Netherlands Antilles", "AN", "ANT"},
	{"New Caledonia", "NC", "NCL"},
	{"New Zealand", "NZ", "NZL"},
	{"Nicaragua", "NI", "NIC"},
	{"Niger", "NE", "NER"},
	{"Nigeria", "NG", "NGA"},
	{"Northern Mariana Islands", "MP", "MNP"},
	{"Norway", "NO", "NOR"},
	{"Oman", "OM", "OMN"},
	{"Pakistan", "PK", "PAK"},
	{"Palau", "PW", "PLW"},
	{"Palestinian Territory", "PS", "PSE"},
	{"Panama", "PA", "PAN"},
	{"Papua New Guinea", "PG", "PNG"},
	{"Paraguay", "PY", "PRY"},
	{"Peru", "PE", "PER"},
	{"Philippines", "PH", "PHL"},
	{"Pitcairn", "PN", "PCN"},
	{"Poland", "PL", "POL"},
	{"Portugal", "PT", "PRT"},
	{"Puerto Rico", "PR", "PRI"},
	{"Qatar", "QA", "QAT"},
	{"Réunion", "RE", "REU"},
	{"Romania", "RO", "ROU"},
	{"Russian Federation", "RU", "RUS"},
	{"Rwanda", "RW", "RWA"},
	{"Saint Kitts and Nevis", "KN", "KNA"},
	{"Saint Lucia", "LC", "LCA"},
	{"Saint Vincent and Grenadines", "VC", "VCT"},
	{"Samoa", "WS", "WSM"},
	{"San Marino", "SM", "SMR"},
	{"Sao Tome and Principe", "ST", "STP"},
	{"Saudi Arabia", "SA", "SAU"},
	{"Senegal", "SN", "SEN"},
	{"Serbia", "RS", "SRB"},
	{"Seychelles", "SC", "SYC"},
	{"Sierra Leone", "SL", "SLE"},
	{"Singapore", "SG", "SGP"},
	{"Slovakia", "SK", "SVK"},
	{"Slovenia", "SI", "SVN"},
	{"Solomon Islands", "SB", "SLB"},
	{"Somalia", "SO", "SOM"},
	{"South Africa", "ZA", "ZAF"},
	{"Spain", "ES", "ESP"},
	{"Sri Lanka", "LK", "LKA"},
	{"Sudan", "SD", "SDN"},
	{"Suriname", "SR", "SUR"},
	{"Swaziland", "SZ", "SWZ"},
	{"Sweden", "SE", "SWE"},
	{"Switzerland", "CH", "CHE"},
	{"Syrian Arab Republic", "SY", "SYR"},
	{"Taiwan (Province of China)", "TW", "TWN"},
	{"Tajikistan", "TJ", "TJK"},
	{"Tanzania", "TZ", "TZA"},
	{"Thailand", "TH", "THA"},
	{"Timor-Leste", "TL", "TLS"},
	{"Togo", "TG", "TGO"},
	{"Tonga", "TO", "TON"},
	{"Trinidad and Tobago", "TT", "TTO"},
	{"Tunisia", "TN", "TUN"},
	{"Turkey", "TR", "TUR"},
	{"Turkmenistan", "TM", "TKM"},
	{"Tuvalu", "TV", "TUV"},
	{"Uganda", "UG", "UGA"},
	{"Ukraine", "UA", "UKR"},
	{"United Arab Emirates", "AE", "ARE"},
	{"United Kingdom", "GB", "GBR"},
	{"United States of America", "US", "USA"},
	{"Uruguay", "UY", "URY"},
	{"Uzbekistan", "UZ", "UZB"},
	{"Vanuatu", "VU", "VUT"},
	{"Venezuela", "VE", "VEN"},
	{"Viet Nam", "VN", "VNM"},
	{"Virgin Islands, US", "VI", "VIR"},
	{"Yemen", "YE", "YEM"},
	{"Zambia", "ZM", "ZMB"},
	{"Zimbabwe", "ZW", "ZWE"},
}

// gets the country using the specified 'alpha-2' identifier
// returns: nil if country not found
func GetByAlpha2(alpha2 string) *Country {
	for i := range Countries {
		if strings.EqualFold(Countries[i].Alpha2, alpha2) {
			return &Countries[i]
		}
	}

	return nil
}

// gets the country using the specified 'alpha-3' identifier
// returns: nil if country not found
func GetByAlpha3(alpha3 string) *Country {
	for i := range Countries {
		if strings.EqualFold(Countries[i].Alpha3, alpha3) {
			return &Countries[i]
		}
	}

	return nil
}
