name: Run tests and upload coverage

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install libpcsclite-dev
        run: |
          sudo apt-get update
          sudo apt-get -y install libpcsclite-dev
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
